doctestquiz/activities/urls.py
from django.urls import path
from activities import views

app_name = "activities"

urlpatterns = [
    path("runner/", views.ActivityRunnerView.as_view(), name="runner"),
    path("editor/", views.ActivityEditorView.as_view(), name="editor"),
    path("<int:uid>/editor/", views.ActivityEditorView.as_view(), name="editor"),
]

doctestquiz/common/urls.py
from django.contrib import admin
from django.urls import path
from snippets.views import SnippetView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", SnippetView.as_view(), name="runcode"),
]

doctestquiz/activities/models.py
from django.db import models
from accounts.models import Account


class Activity(models.Model):
    uid = models.AutoField(primary_key=True)
    description = models.TextField()
    function_header = models.CharField(max_length=48)
    attempts = models.SmallIntegerField(default=3, help_text="Use -1 for unlimited attempts")
    is_hidden = models.BooleanField(default=False, editable=False)


class Doctest(models.Model):
    uid = models.AutoField(primary_key=True)
    input = models.CharField(max_length=64)
    output = models.CharField(max_length=64)
    is_hidden = models.BooleanField(default=False)
    activity = models.ForeignKey(to=Activity, related_name="doctests", on_delete=models.CASCADE)


class Snippet(models.Model):
    uid = models.AutoField(primary_key=True)
    code = models.TextField()
    activity = models.ForeignKey(to=Activity, related_name="snippets", on_delete=models.CASCADE)
    programmer = models.ForeignKey(to=Account, related_name="snippets", on_delete=models.SET_NULL, null=True)

doctestquiz/activities/forms.py
import epicbox
from django import forms
from activities.models import Activity, Doctest


epicbox.configure(profiles=[epicbox.Profile("python", "python:3.8.5-alpine")])
limits = {"cputime": 3, "realtime": 10, "memory": 16, "processes": 1}


class ActivityRunnerForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = "__all__"
        labels = {"source_code": "Source Code"}


class ActivityEditorForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = "__all__"
        widgets = {"function_header": forms.TextInput(attrs={"placeholder": "foo(bar=None)"})}

    def clean_attempts(self):
        if self.cleaned_data["attempts"] < 1 and self.cleaned_data["attempts"] != -1:
            raise forms.ValidationError("The number of attempts is invalid.")
        return self.cleaned_data["attempts"]


class DoctestForm(forms.ModelForm):
    class Meta:
        model = Doctest
        fields = "__all__"
        widgets = {
            "input": forms.TextInput(attrs={"placeholder": ">>> foo()"}),
            "output": forms.TextInput(attrs={"placeholder": "'bar'"}),
        }


DoctestsFormSet = forms.inlineformset_factory(Activity, Doctest, form=DoctestForm, extra=0, min_num=1)

doctestquiz/activities/views.py
from django.views import View
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect
from common.mixins import NextPageMixin
from activities.forms import ActivityEditorForm, ActivityRunnerForm, DoctestsFormSet
from activities.models import Activity, Doctest


class ListView(View):
    def get(self, request):
        activities = Activity.objects.filter(is_hidden=False)
        return render(request=request, template_name="activities/list.html", context={"activities": activities})


class ActivityRunnerView(View):
    def get(self, request):
        form = ActivityRunnerForm()
        return render(request=request, template_name="activities/runner.html", context={"form": form})

    def post(self, request):
        epicbox.configure(profiles=[epicbox.Profile("python", "python:3.8.5-alpine")])

        form = ActivityRunnerForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["source_code"]
            content += "\nimport doctest\ndoctest.testmod()"

            limits = {"cputime": 3, "realtime": 10, "memory": 16, "processes": 1}
            files = [{"name": "main.py", "content": content.encode("utf-8")}]
            result = epicbox.run("python", "python3 main.py", files=files, limits=limits)

            status = ""

            if result["exit_code"] != 0:
                if result["timeout"]:
                    status += "The runner has timed out. Are you entering an infinite loop?\n\n"
                elif result["oom_killed"]:
                    status += "The runner has run out of memory. Are you creating too many objects?\n\n"
                else:
                    status += "Check the output for errors.\n\n"

                status += "Exit code: " + str(result["exit_code"]) + "\n"
                output = result["stderr"].decode("utf-8")
                color = "danger"
            else:
                status += "Success!" + "\n\n"
                status += "Exit code: " + str(result["exit_code"]) + "\n"
                output = result["stdout"].decode("utf-8")
                color = "success"

            status += "Total execution time: " + str(result["duration"])

            return render(
                request=request,
                template_name="activities/runner.html",
                context={"form": form, "output": output, "status": status, "color": color},
            )
        return render(request=request, template_name="activities/runner.html", context={"form": form})


class ActivityEditorView(NextPageMixin, View):
    def get(self, request, uid=None):
        if uid is None:
            form = ActivityEditorForm()
            formset = DoctestsFormSet()
        else:
            try:
                form = ActivityEditorForm(instance=Activity.objects.get(uid=uid))
                formset = DoctestsFormSet(instance=Activity.objects.get(uid=uid))
            except (TypeError, ValueError, OverflowError, Activity.DoesNotExist):
                messages.add_message(request, messages.ERROR, "The activity doesn't exist.")
                return HttpResponseRedirect("/")
        return render(
            request=request, template_name="activities/editor.html", context={"form": form, "formset": formset}
        )

    def post(self, request, uid=None):
        if uid is None:
            form = ActivityEditorForm(request.POST)
            formset = DoctestsFormSet(request.POST)
            if form.is_valid():
                activity = form.save(commit=False)
                formset = DoctestsFormSet(request.POST, instance=activity)
                if formset.is_valid():
                    activity.save()
                    form.save_m2m()
                    formset.save()
                    messages.add_message(request, messages.SUCCESS, "The activity has been successfully created.")
                    return HttpResponseRedirect(self.next)
        else:
            try:
                form = ActivityEditorForm(request.POST, instance=Activity.objects.get(uid=uid))
                formset = DoctestsFormSet(request.POST, instance=Activity.objects.get(uid=uid))
                if form.is_valid() and formset.is_valid():
                    form.save()
                    formset.save()
                    messages.add_message(request, messages.SUCCESS, "The activity has been successfully edited.")
                    return HttpResponseRedirect(self.next)
            except (TypeError, ValueError, OverflowError, Activity.DoesNotExist):
                messages.add_message(request, messages.ERROR, "The activity doesn't exist.")
                return HttpResponseRedirect("/")
        return render(
            request=request, template_name="activities/editor.html", context={"form": form, "formset": formset}
        )

doctestquiz/activities/templates/activities/editor.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block title %}Activity Editor{% endblock title %}
{% block extra_head %}
<script src="{% static 'js/jquery.formset.js' %}"></script>
{% endblock extra_head %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.description|as_crispy_field }}
            <div id="div_id_function_header" class="form-group">
                <label for="id_function_header" class=" requiredField">Function header<span class="asteriskField">*</span>
                </label>
                <div class="">
                    {% crispy_field form.function_header 'class' 'form-control text-monospace' %}
                    {% if form.function_header.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.function_header.errors %}
                        <strong>{{ error }}</strong>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            {{ form.attempts|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            <label for="id_doctests_table">Doctests</label>
            (Every failed attempt will reveal a hidden doctest)
            <table id="id_doctests_table" class="table">
                <thead>
                    <tr>
                        <th scope="col" width="45%">Input</th>
                        <th scope="col" width="45%">Output</th>
                        <th scope="col" width="5%">Hidden</th>
                        <th scope="col" width="5%"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for form in formset.forms %}
                    {% for field in form.hidden_fields %}{{ field }}{% endfor %}
                    <tr id="{{ form.prefix }}-row">
                        <td>
                            {% crispy_field form.input 'class' 'form-control form-control-sm text-monospace' %}
                            {% if form.input.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.input.errors %}
                                <strong>{{ error }}</strong>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </td>
                        <td>
                            {% crispy_field form.output 'class' 'form-control form-control-sm text-monospace' %}
                            {% if form.output.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.output.errors %}
                                <strong>{{ error }}</strong>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </td>
                        <td>
                            {% crispy_field form.is_hidden 'class' 'form-control form-control-sm' %}
                            {% if form.is_hidden.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.is_hidden.errors %}
                                <strong>{{ error }}</strong>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </td>
                        <td class="btn-delete-container">{% if form.instance.pk %}{{ form.DELETE }}{% endif %}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p>
                {{ formset.management_form }}
            </p>
        </div>
    </div>
    <hr>
    <div class="form-actions">
        <button id="submitButton" type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
<script type="text/javascript">
    $(function () {
        $('#id_doctests_table tbody tr').formset({
            prefix: 'doctests'
        })
    })
</script>
{% endblock content %}

doctestquiz/activities/templates/activities/list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Activities{% endblock title %}
{% block subtitle %}View the list of public activities.{% endblock subtitle %}

{% block content %}
<table id="jsTable" class="table list-view nowrap" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Type</th>
            <th scope="col">
                <a class="btn btn-sm btn-success" href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">
                    <i class="fas fa-plus fa-fw"></i>
                    Create Account
                </a>
            </th>
        </tr>
    </thead>
    <tbody>
        {% for account in accounts %}
        <tr>
            <td>{{ account.first_name }}</td>
            <td>{{ account.last_name }}</td>
            <td><a href="mailto:{{ account.email }}">{{ account.email }}</a></td>
            <td>{{ account.is_superuser|yesno:"Manager,Developer" }}</td>
            <td>
                <a class="btn btn-sm btn-info" href="{% url 'accounts:detail' uid=account.uid %}" data-toggle="tooltip"
                    title="View Account">
                    <i class="fas fa-eye fa-fw"></i>
                </a>
                <a class="btn btn-sm btn-warning" href="{% url 'accounts:edit' uid=account.uid %}?next={{ request.get_full_path }}"
                    data-toggle="tooltip" title="Edit Account">
                    <i class="fas fa-pen fa-fw"></i>
                </a>
                <a class="btn btn-sm btn-danger" href="{% url 'accounts:delete' uid=account.uid %}?next={{ request.get_full_path }}"
                    data-toggle="tooltip" title="Delete Account">
                    <i class="fas fa-trash fa-fw"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

doctestquiz/activities/templates/activities/runner.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Activity Runner{% endblock title %}

{% block extra_head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.57.0/codemirror.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.57.0/codemirror.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.57.0/mode/python/python.min.js"></script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12 col-xl-6">
        <form id="codeForm" novalidate method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-actions">
                <button id="submitButton" type="submit" class="btn btn-success btn-detail">
                    <i class="fas fa-play fa-fw mr-1"></i>
                    Execute
                </button>
            </div>
        </form>
    </div>
    <div class="col-12 col-xl-6">
        <label for="id_code" class="control-label requiredField">Output</label>
        <div style="background-color: black; color: white; border-radius: 8px; padding: 16px; word-wrap: break-word;">
            {{ output|linebreaksbr }}
        </div>
        <div class=" mt-3 alert alert-{{color}}" style="border-radius: 8px; padding: 16px;">
            {{ status|linebreaksbr }}
        </div>
    </div>
</div>
<script>
    window.myCodeMirror = CodeMirror.fromTextArea(document.getElementById("id_source_code"), {
        lineNumbers: true,
        indentUnit: 4,
        indentWithTabs: false,
        autofocus: true,
        mode: 'python',
    });
    $(document).ready(function () {
        $("#codeForm").submit(function (e) {
            $("#submitButton").attr("disabled", true);
            $(".spinner-grow").removeClass("d-none");
        });
    });
</script>
{% endblock content %}

doctestquiz/common/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no">
    <title>DoctestQuiz</title>
    <link rel='shortcut icon' type='image/x-icon' href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,500&display=swap">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/v/bs4/dt-1.10.21/r-2.2.5/datatables.min.css">
    <link rel="stylesheet" href="{% static 'css/doctestquiz.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/bs4/dt-1.10.21/r-2.2.5/datatables.min.js"></script>
    {% comment %}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/doctestquiz.js' %}"></script>{% endcomment %}
    {% block extra_head %}{% endblock extra_head %}
</head>

<body>
    {% comment %}{% include "includes/sidebar.html" %}{% endcomment %}
    <div class="main">
        {% include "includes/messages.html" %}
        <h1>{% block title %}{% endblock title %}</h1>
        <hr>
        {% block content %}{% endblock content %}
    </div>
</body>

</html>

doctestquiz/common/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock title %}
{% block subtitle %}Access quick actions customized for your account.{% endblock subtitle %}

{% block content %}
<div class="dashboard-body core-font">
    <ul>
        <li>
            <div class="card">
                <div class="card-header w-100">
                    <h5 class="text-uppercase m-0">Create Invoice</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">Create an invoice for your existing partners!</p>
                </div>
                <div class="card-footer w-100">
                    <a class="btn btn-success" href="{% url 'invoices:create' %}"><i class="fas fa-plus fa-fw"></i></a>
                </div>
            </div>
        </li>
        <li>
            <div class="card">
                <div class="card-header w-100">
                    <h5 class="text-uppercase m-0">Create Partner</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">Create a new partner!</p>
                </div>
                <div class="card-footer w-100">
                    <a class="btn btn-success" href="{% url 'partners:create' %}"><i class="fas fa-plus fa-fw"></i></a>
                </div>
            </div>
        </li>
        {% for shift in shifts %}
        <li>
            <div class="card">
                <div class="card-header w-100">
                    <h5 class="text-uppercase m-0">
                        Shift <span class="text-secondary">{{ shift.description }}</span>
                    </h5>
                </div>
                <div class="card-body">
                    <p>You have not associated this shift with a project. If you don't do so, this time might not be invoiced!</p>
                </div>
                <div class="card-footer w-100">
                    <a class="btn btn-warning" href="{% url 'accounts:shifts_edit' uid=shift.uid %}"><i class="fas fa-pen fa-fw"></i></a>
                </div>
            </div>
        </li>
        {% endfor %}
        {% for invoice in invoices %}
        <li>
            <div class="card">
                <div class="card-header w-100">
                    <h5 class="text-uppercase m-0">Invoice <span class="text-secondary">{{ invoice.invoice_id }}</span>
                    </h5>
                </div>
                <div class="card-body">
                    {% if invoice.status == 2 %}
                    <p>The partner failed to pay on time. Make sure to contact them and/or suspend their services!</p>
                    {% else %}
                    <p>The status of this invoice is not final so we thought it might be of interest!</p>
                    {% endif %}
                    <p class="card-text">{{ invoice.get_html_status }}</p>
                </div>
                <div class="card-footer w-100">
                    <a class="btn btn-info" href="{% url 'invoices:pdf' uid=invoice.uid %}"><i class="fas fa-file-pdf fa-fw"></i></a>
                    <a class="btn btn-warning" href="{% url 'invoices:edit' uid=invoice.uid %}"><i class="fas fa-pen fa-fw"></i></a>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

doctestquiz/common/templates/email.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>

<head>
    <title>
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style type="text/css">
        body {
            background-color: #FFFFFF;
            width: 100%;
            padding: 0;
            margin: 0;
        }

        #main {
            width: 100%;
            padding: 0;
            margin: 0;
        }

        #header {
            margin: 0;
            padding: 16px 0 16px;
            font-family: 'Arial', sans-serif;
            font-weight: 700;
            font-size: 32px;
            color: #000000;
            text-align: center;
            border-bottom: 4px solid #202020;
        }

        #message {
            padding: 0;
            margin: 128px auto 128px;
            width: 480px;
            font-family: 'Arial', sans-serif;
            font-weight: 700;
            font-size: 48px;
            color: #000000;
            text-align: center;
        }

        #message>p {
            margin: 0 0 64px;
            padding: 0
        }

        #message>a {
            margin: 0;
            padding: 0;
            font-size: 24px;
            text-decoration: none;
        }

        .footer {
            padding: 8px;
            border-top: 4px solid #202020;
            background: #000000;
            color: #808080;
            font-family: Arial;
            text-transform: uppercase;
            font-weight: 500
        }

        .footer p {
            margin: 8px;
            font-size: 8px;
            text-align: center;
        }

        .footer a {
            font-size: 12px;
            text-align: center;
            text-decoration: none;
        }

        .footer-logos {
            text-align: center;
        }
    </style>
</head>

<body>
    <div id="main">
        <div>
            <h1 id="header">Business Tracker</h1>
        </div>
        <div id="message">
            <p>{{ message }}</p>
            <a href="{{ url }}">{{ button }}</a>
        </div>
        <div class="footer footer-logos">
            <p>Copyright &copy; 2020</p>
            <a href="https://novawebdevelopment.com/">NOVA Web Development</a>
        </div>
    </div>
</body>

</html>

doctestquiz/common/templates/includes/messages.html
{% if messages %}
<div class="fixed-top">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true"><i class="fas fa-times"></i></span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

doctestquiz/common/templates/includes/sidebar.html
{% load static %}
<button type="button" id="chev" class="btn sidenav-button" onclick="toggleSidebar()">
    <i class="fas fa-chevron-right"></i>
</button>
<div class="sidenav">
    <a class="link-unstyled" href="https://businesstracker.org/" style="margin: 0">
        <img class="img-fluid d-block mx-auto" src="{% static 'img/logo.png' %}">
    </a>
    <div class="sidenav-controls">
        {% if user.is_authenticated %}
        <a href="{% url 'dashboard' %}"><i class="fas fa-clone fa-fw mr-2"></i>Dashboard</a>
        <a href="{% url 'accounts:shifts_create' %}"><i class="fas fa-clock fa-fw mr-2"></i>Track Time</a>
        <div>
            <hr>
        </div>
        {% if user.is_superuser %}
        <a href="{% url 'accounts:list' %}"><i class="fas fa-users fa-fw mr-2"></i>Accounts</a>
        {% endif %}
        <a href="{% url 'invoices:list' %}"><i class="fas fa-file-invoice-dollar fa-fw mr-2"></i>Invoices</a>
        <a href="{% url 'partners:list' %}"><i class="fas fa-user-friends fa-fw mr-2"></i>Partners</a>
        <a href="{% url 'projects:list' %}"><i class="fas fa-code-branch fa-fw mr-2"></i>Projects</a>
        <a href="{% url 'servers:list' %}"><i class="fas fa-server fa-fw mr-2"></i>Servers</a>
        <div>
            <hr>
        </div>
        {% if user.is_superuser %}
        <a href="{% url 'settings' %}"><i class="fas fa-cog fa-fw mr-2"></i>Settings</a>
        {% endif %}
        <a href="{% url 'accounts:detail' uid=user.uid %}?personal=true"><i class="fas fa-user fa-fw mr-2"></i>My Account</a>
        <a href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt fa-fw mr-2"></i>Log out</a>
        {% else %}
        <a href="{% url 'accounts:login' %}"><i class="fas fa-sign-in-alt fa-fw mr-2"></i>Login</a>
        <a href="{% url 'accounts:password_reset' %}"><i class="fas fa-key fa-fw mr-2"></i>Reset Password</a>
        {% endif %}
    </div>
    <a class="link-unstyled" href="https://novawebdevelopment.org/" style="margin: 0">
        <img class="img-fluid d-block mx-auto" src="{% static 'img/novawebdevelopment.png' %}">
    </a>
</div>

doctestquiz/common/templates/settings.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extra_head %}
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
{% endblock extra_head %}

{% block title %}Settings{% endblock title %}
{% block subtitle %}Set up Business Tracker the way you want.{% endblock subtitle %}

{% block content %}
<form novalidate enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <div id="div_{{ form.invoice_template.id_for_label }}" class="form-group">
        <label for="{{ form.invoice_template.id_for_label }}">{{ form.invoice_template.label }}</label>
        <div class="custom-file">
            <input type="file" name="{{ form.invoice_template.name }}" class="custom-file-input"
                id="{{ form.invoice_template.id_for_label }}" accept="application/pdf">
            <label class="custom-file-label" for="{ form.invoice_template.id_for_label }}">Choose PDF file</label>
            {% if form.invoice_template.help_text %}
            <small id="hint_{{ form.invoice_template.name }}" class="form-text text-muted">{{ form.invoice_template.help_text }}</small>
            {% endif %}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.email_host|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.email_port|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.email_user|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            <div id="div_id_email_password" class="form-group">
                <label for="id_email_password" class="">
                    Email Password
                </label>
                <div class="">
                    <div class="input-group mb-3">
                        <input type="password" name="email_password" value="{{ form.email_password.value }}"
                            class="textinput textInput form-control" id="id_email_password">
                        <div class="input-group-append">
                            <button type="button" id="emailPasswordButton" class="btn btn-outline-info" data-toggle="button"
                                id="emailPasswordButton"><i class="fas fa-eye fa-fw"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div id="div_{{ form.email_use_tls.id_for_label }}" class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" name="{{ form.email_use_tls.name }}"
                id="{{ form.email_use_tls.id_for_label }}" {% if form.email_use_tls.value %} checked {% endif %}>
            <label class="custom-control-label" for="{{ form.email_use_tls.id_for_label }}">{{ form.email_use_tls.label }}</label>
            {% if form.email_use_tls.help_text %}
            <small id="hint_{{ form.email_use_tls.name }}" class="form-text text-muted">{{ form.email_use_tls.help_text }}</small>
            {% endif %}
        </div>
    </div>
    <hr>
    {{ form.weekly_hours|as_crispy_field }}
    {{ form.overdue_days|as_crispy_field }}
    {{ form.billing_message|as_crispy_field }}
    <div class="form-group">
        <div id="div_{{ form.auto_email.id_for_label }}" class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" name="{{ form.auto_email.name }}" id="{{ form.auto_email.id_for_label }}"
                {% if form.auto_email.value %} checked {% endif %}>
            <label class="custom-control-label" for="{{ form.auto_email.id_for_label }}">{{ form.auto_email.label }}</label>
            {% if form.auto_email.help_text %}
            <small id="hint_{{ form.auto_email.name }}" class="form-text text-muted">{{ form.auto_email.help_text }}</small>
            {% endif %}
        </div>
    </div>
    <hr>
    {{ form.linode_api_token|as_crispy_field }}
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-primary btn-detail" href="{% url 'dump_json' %}">
            <i class="fas fa-save fa-fw mr-1"></i>
            Dump JSON
        </a>
        <a class="btn btn-primary btn-detail" href="{% url 'dump_xml' %}">
            <i class="fas fa-save fa-fw mr-1"></i>
            Dump XML
        </a>
    </div>
</form>
<script>
    $(document).ready(function () {
        bsCustomFileInput.init()
    })
</script>
{% endblock content %}